### PR TITLE
Fix cost arbitrator called twice #patch

### LINKED ISSUE #62: getCommand is being called twice in CostArbitrator
Since the `CostArbitrator` calls `getCommand` during [`sortOptionsByGivenPolicy`](https://github.com/KIT-MRT/arbitration_graphs/blob/main/include/arbitration_graphs/cost_arbitrator.hpp#L121C61-L121C67), the `getCommand` is being called twice.

`getCommand` might be an expensive operation, so that's not ideal. One solution would be to cache the result of `getCommand` on the user end but of course that's not the best solution.

Another idea could be the following:

Instead of calling `option->behavior->getCommand`, `Option` could implement a wrapper around the behavior's `getCommand`. The `Option` class would then receive a `util_caching::Cache<Command>` and only actually call the `getCommand` of the underlying behavior if it has not been called before in the same time step.

### PR DESCRIPTION
**Pull request by ll-nick**
Closes #62 

The `CostArbitrator` calls `getCommand` twice. Once in `getAndVerifyCommand` like all verifier types but also once in `sortOptionsByGivenPolicy` since the command is required to estimate the cost.
The call to `getCommand` can potentially be quite expensive, though. Therefore, this PR adds a cache for it inside the `Arbitrator::Option` class. When computing a command, the arbitrator now doesn't call the behavior directly anymore but instead calls the wrapper inside the `Option` class. Should the function be called two or more times inside a single time step, the cached command is returned and the behavior is not called again.

### CODE REVIEW

File: test/cost_arbitrator.cpp [hunk 1]
```diff
@@ -116,6 +116,36 @@ TEST_F(CostArbitratorTest, BasicFunctionality) {
...
+    EXPECT_EQ(1, testBehaviorMidCost->getCommandCounter_);
+
+    time = time + Duration(1);
+
+    // The cached command should be invalidated after the time has passed
+    // Therefore the behavior should be called again once for the new time
+    EXPECT_EQ("mid_cost", testCostArbitrator.getCommand(time));
+    EXPECT_EQ(2, testBehaviorMidCost->getCommandCounter_);
+    EXPECT_EQ("mid_cost", testCostArbitrator.getCommand(time));
+    EXPECT_EQ(2, testBehaviorMidCost->getCommandCounter_);
```
Comment (orzechow) [inline test/cost_arbitrator.cpp:146]: Very well, this is important to test :+1:

**Review by orzechow — APPROVED** [review]
Thanks a lot! :+1:

**Comment by ll-nick** [comment]
@orzechow Just FYI:

We ran into an issue because of this. I wouldn't necessarily say that it's an error in the library but something to be aware of when using it. When using a behavior component with a cost arbitrator, this change will result in the following order of calls on the behavior component, when it has never been called before:

During the sorting of the cost estimators options:
1. `gainControl`
2. `getCommand` (it's actually computed here)
3. `loseControl`

When actually calling the command:
1. `gainControl`
2. `getCommand` (the cached version)

In our specific behavior component, we set a class variable required for the commitment condition during `getCommand` which was reset again during `loseControl`. Since `getCommand` is now just returning the cached value, the variable was broke the behavior's commitment.

I suppose having these side effects in the `getCommand` function is not very clean anyway so I now solved that differently.
